services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: mypostgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  db-service:
    build:
      context: ./db
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - WAIT_HOSTS=postgres:5432

  api-service:
    build:
      context: ./apiservice
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db-service
    environment:
      - WAIT_HOSTS=db-service:8080

volumes:
  postgres_data:
